### ISSUE TITLE
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\{user}\\AppData\\Local\\Temp\\tmp147jmo5w.sqlite'

### ISSUE THREAD

**Issue by HengyueLi** [borisbabic/browser_cookie3#46]
OS: windows10
Browser: Chrome

I do not know how to reproduce this proble. I meet the same problem several month ago. At that time, I fixed it by clearning all data in browser. This should be related to browser_cookie3 since the problem is shown by the most simple code shown in the introduciton.
I tried to reboot OS, browser.

(By the way, I do not have admin permisson to this PC)

related error reports:

```
Exception ignored in: <function Chrome.__del__ at 0x0000024764E59730>
Traceback (most recent call last):
  File "c:\users\{user}\appdata\local\continuum\miniconda3\lib\site-packages\browser_cookie3\__init__.py", line 148, in __del__
    os.remove(self.tmp_cookie_file)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\{user}\\AppData\\Local\\Temp\\tmp2hb41qrw.sqlite'
Exception ignored in: <function Chrome.__del__ at 0x0000024764E59730>
Traceback (most recent call last):
  File "c:\users\{user}\appdata\local\continuum\miniconda3\lib\site-packages\browser_cookie3\__init__.py", line 148, in __del__
    os.remove(self.tmp_cookie_file)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\{user}\\AppData\\Local\\Temp\\tmpot3jbe_8.sqlite'
```

**Comment by netchose** [comment]
Chrome version ?

**Comment by HengyueLi** [comment]
`80.0.3987.87 (Official Build) (64-bit) (cohort: 80_87_Win)`

I copied additioonal info from `chrome://version/`

```


Google Chrome | 80.0.3987.87 (Official Build) (64-bit) (cohort: 80_87_Win)
-- | --
Revision | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
OS | Windows 10 OS Version 1803 (Build 17134.1246)
JavaScript | V8 8.0.426.16
Flash | 32.0.0.321 C:\Users\{user}\AppData\Local\Google\Chrome\User Data\PepperFlash\32.0.0.321\pepflashplayer.dll
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36
Command Line | "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --flag-switches-begin --flag-switches-end --enable-audio-service-sandbox
Executable Path | C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
Profile Path | C:\Users\{user}\AppData\Local\Google\Chrome\User Data\Default
Variations | bcb409bf-42f863a2



```

**Comment by HengyueLi** [comment]
PS:
Now on my PC, the problem can be reproduced easily. But I do not know how to let you guys to reproduce it. If some tests are needed, please tell me.

**Comment by netchose** [comment]
same as  https://github.com/borisbabic/browser_cookie3/issues/44 : change in the encryption method with chrom >= v80

**Comment by Me-TheKing** [comment]
I have the same problem and i solve it by adding the domain_name when calling the cookie_file.

```
chromecookies = os.path.join(os.path.expandvars("%userprofile%"),"AppData\\Local\\Google\\Chrome\\User Data\\Profile 1\\Cookies")
cookiejar = browser_cookie3.chrome(cookie_file=chromecookies, domain_name="site.com"
```

you can see my issues #42

**Comment by HengyueLi** [comment]
@Me-TheKing  Append the domain name seems working. However, for my case, when I visit url1, I need to use several other cookies suck as url2,url3. It there a way to append multiple domain names? Moreover, can I use something like "*example.com" to match?

**Comment by HengyueLi** [comment]
I feel that I got your point. But what should I do specifically? @netchose

**Comment by netchose** [comment]
I switched to Firefox while waiting for a fix.

**Comment by Me-TheKing** [comment]
> @Me-TheKing Append the domain name seems working. However, for my case, when I visit url1, I need to use several other cookies suck as url2,url3. It there a way to append multiple domain names? Moreover, can I use something like "*example.com" to match?

if you know the names of the domains of your urls then you can make a list of your domains and make your domin_name read from that list. Or you can switch to Firefox as @netchose say.

**Comment by brooksmcmillin** [comment]
My pull request should fix this, I have it working both with Chrome v80 as well as the previous versions (at least v79) in Windows. 

https://github.com/borisbabic/browser_cookie3/pull/47

**Comment by HengyueLi** [comment]
Problem solved by reinstalling the new version updated today. Great!

**Comment by skyfire000** [comment]
I still have the same problem, with version 0.10.2

My OS : Win10 +  Chromium Edge  + Winpython 3.8

> Exception ignored in: <function Chrome.__del__ at 0x0000013B8EAE2820>
Traceback (most recent call last):
  File "G:\Wpy\WPy64-3810\python-3.8.1.amd64\lib\site-packages\browser_cookie3\__init__.py", line 174, in __del__
    os.remove(self.tmp_cookie_file)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'E:\\Personal\\Temp\\tmpvxumhpzf.sqlite'
Traceback (most recent call last):
  File "<tmp 2>", line 3, in <module>
    cj = browser_cookie3.chrome(cookie_file='C:\\Users\\JX\\AppData\\Local\\Microsoft\\Edge\\User Data\\Default\\Cookies')
  File "G:\Wpy\WPy64-3810\python-3.8.1.amd64\lib\site-packages\browser_cookie3\__init__.py", line 399, in chrome
    return Chrome(cookie_file, domain_name).load()
  File "G:\Wpy\WPy64-3810\python-3.8.1.amd64\lib\site-packages\browser_cookie3\__init__.py", line 211, in load
    value = self._decrypt(item[5], item[6])
  File "G:\Wpy\WPy64-3810\python-3.8.1.amd64\lib\site-packages\browser_cookie3\__init__.py", line 240, in _decrypt
    if not self.key:
AttributeError: 'Chrome' object has no attribute 'key'

**Comment by giserjing** [comment]
I have also been troubled by this problem for a long time, and I solved it by referring to this answer:module 'Crypto.Cipher.AES' has no attribute 'MODE_CCM' even though pycrypto installed[](https://stackoverflow.com/questions/43987779/python-module-crypto-cipher-aes-has-no-attribute-mode-ccm-even-though-pycry)

**Comment by giserjing** [comment]
I have also been troubled by this problem for a long time, and I solved it by referring to this answer:[module 'Crypto.Cipher.AES' has no attribute 'MODE_CCM' even though pycrypto installed](https://stackoverflow.com/questions/43987779/python-module-crypto-cipher-aes-has-no-attribute-mode-ccm-even-though-pycry)

**Comment by alzamer2** [comment]
it seem this isssue returened
it give that line
`'FROM cookies WHERE host_key like "%{}%";'.format(self.domain_name))`
"�'♠���X�u☺v��YOs����►c����RK��n�fq������M��s��|,1-8 column 'encrypted_value' with text 'v10p
�Z��e▲4▼���'"
the error is with value that cant encode to utf-8
i was able to fix the code by adding
"con.text_factory = bytes" 
after line 263 "con = sqlite3.connect(self.tmp_cookie_file)"
and change line 293 "c = create_cookie(host., path., secure, expires, name., value)" to c = create_cookie(host.decode(), path.decode(), secure, expires, name.decode(), value)

of course i'm not sure if the code is working for all situation now or its only for me that why i did not make pull requests
if any1 has same issue as me can you test this fix ?

**Comment by rafiibrahim8** [comment]
@alzamer2 There is an open pull request (#79) fixing this issue. You can wait until it gets merged into master. Or you can install it directly from the source branch using:
`python3 -m pip install --upgrade git+https://github.com/rafiibrahim8/browser_cookie3.git@chrome_90_fix`
