### ISSUE TITLE
chrome failed

### ISSUE THREAD

**Issue by cnglen** [borisbabic/browser_cookie3#55]
Version 80.0.3987.122 (Official Build) (64-bit)

> 
In [32]: cj = browser_cookie3.chrome()
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-32-664d28acebc7> in <module>
----> 1 cj = browser_cookie3.chrome()

/mnt/os/opt/anaconda3/lib/python3.7/site-packages/browser_cookie3/__init__.py in chrome(cookie_file, domain_name)
    463     domain name to only load cookies from the specified domain
    464     """
--> 465     return Chrome(cookie_file, domain_name).load()
    466 
    467 

/mnt/os/opt/anaconda3/lib/python3.7/site-packages/browser_cookie3/__init__.py in load(self)
    267                     expires = expires.timestamp()
    268 
--> 269             value = self._decrypt(item[5], item[6])
    270             c = create_cookie(host, path, secure, expires, name, value)
    271             cj.set_cookie(c)

/mnt/os/opt/anaconda3/lib/python3.7/site-packages/browser_cookie3/__init__.py in _decrypt(self, value, encrypted_value)
    320         decrypted = cipher.feed(encrypted_value[:encrypted_value_half_len])
    321         decrypted += cipher.feed(encrypted_value[encrypted_value_half_len:])
--> 322         decrypted += cipher.feed()
    323         return decrypted.decode("utf-8")
    324 

/mnt/os/opt/anaconda3/lib/python3.7/site-packages/pyaes/blockfeeder.py in feed(self, data)
    167         # Finalize; process the spare bytes we were keeping
    168         if data is None:
--> 169             result = self._final(self._buffer, self._padding)
    170             self._buffer = None
    171             return result

/mnt/os/opt/anaconda3/lib/python3.7/site-packages/pyaes/blockfeeder.py in _block_final_decrypt(self, data, padding)
     75 def _block_final_decrypt(self, data, padding = PADDING_DEFAULT):
     76     if padding == PADDING_DEFAULT:
---> 77         return strip_PKCS7_padding(self.decrypt(data))
     78 
     79     if padding == PADDING_NONE:

/mnt/os/opt/anaconda3/lib/python3.7/site-packages/pyaes/util.py in strip_PKCS7_padding(data)
     56 
     57     if pad > 16:
---> 58         raise ValueError("invalid padding byte")
     59 
     60     return data[:-pad]

ValueError: invalid padding byte

**Comment by aulismedia** [comment]
The same problem here. 

File "/usr/local/lib/python3.5/dist-packages/pyaes/blockfeeder.py", line 169, in feed
    result = self._final(self._buffer, self._padding)
  File "/usr/local/lib/python3.5/dist-packages/pyaes/blockfeeder.py", line 77, in _block_final_decrypt
    return strip_PKCS7_padding(self.decrypt(data))
  File "/usr/local/lib/python3.5/dist-packages/pyaes/util.py", line 58, in strip_PKCS7_padding
    raise ValueError("invalid padding byte")
ValueError: invalid padding byte

**Comment by dlenski** [comment]
I assume that what you are actually using is **Chromium** (the open-source version, not Google-branded **Chrome**) on Linux.

If so, my recent PR https://github.com/borisbabic/browser_cookie3/pull/62 should fix this.

**Comment by Battleman** [comment]
I have the same error. just using `browser_cookies3.chrome()` yields a similar error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/storage/anaconda3/envs/zoomdl/lib/python3.7/site-packages/browser_cookie3/__init__.py", line 465, in chrome
    return Chrome(cookie_file, domain_name, key_file).load()
  File "/storage/anaconda3/envs/zoomdl/lib/python3.7/site-packages/browser_cookie3/__init__.py", line 269, in load
    value = self._decrypt(item[5], item[6])
  File "/storage/anaconda3/envs/zoomdl/lib/python3.7/site-packages/browser_cookie3/__init__.py", line 322, in _decrypt
    decrypted += cipher.feed()
  File "/storage/anaconda3/envs/zoomdl/lib/python3.7/site-packages/pyaes/blockfeeder.py", line 169, in feed
    result = self._final(self._buffer, self._padding)
  File "/storage/anaconda3/envs/zoomdl/lib/python3.7/site-packages/pyaes/blockfeeder.py", line 77, in _block_final_decrypt
    return strip_PKCS7_padding(self.decrypt(data))
  File "/storage/anaconda3/envs/zoomdl/lib/python3.7/site-packages/pyaes/util.py", line 58, in strip_PKCS7_padding
    raise ValueError("invalid padding byte")
ValueError: invalid padding byte
```

Sadly #62 doesn't seem to fix it. I cloned the repo, applied your fix manually. And calling `python __init__.py` yields the exact same error.

On my system, I have chrome, chromium, brave, and 2 firefox (nightly and ESR). I'm not sure if the presence of multiple chromium-based triggers the problem.

I'm on Debian stable with gnome too. Obviously with latest version 0.11.2

**Comment by dlenski** [comment]
> Sadly #62 doesn't seem to fix it. I cloned the repo, applied your fix manually. And calling python __init__.py yields the exact same error.
> 
> On my system, I have chrome, chromium, brave, and 2 firefox (nightly and ESR). **I'm not sure if the presence of multiple chromium-based triggers the problem.**

Yes, that is quite likely an issue.

Can you confirm using the Keyring UI… do you have both a `Chrome Safe Storage` and a `Chromium Safe Storage` keyring? (Those should be the exact names.)

Which of these paths contain your cookie files? https://github.com/borisbabic/browser_cookie3/blob/master/__init__.py#L183-L187

**Comment by Battleman** [comment]
>do you have both a `Chrome Safe Storage` and a `Chromium Safe Storage` keyring?

Yes, I do

>Check which of these paths actually contain the cookie files on your system?

I have cookies at both  `'~/.config/google-chrome/Default/Cookies'` and `'~/.config/chromium/Default/Cookies'` (as well as  `.config/BraveSoftware/Brave-Browser/Default/Cookies`, for my Brave browser).

>What are the versions of the Chrome and Chromium browsers

dpkg reports
```
chromium                                83.0.4103.116-1~deb10u3
google-chrome-stable                    85.0.4183.121-1
```

**Comment by dlenski** [comment]
@Battleman I updated the PR so that it tries to use the Chromium keyring _only_ with the Chromium cookie file, and the Chrome keyring _only_ with the Chrome cookie file, etc. (Also, it will use the **Chromium** cookies, not the **Chrome** cookies, by default… if it finds both keyrings.)

Can you please test and see if this works? 

I don't know anything about how Brave stores its cookie passwords, so you'd have to figure that part out yourself.

**Comment by Battleman** [comment]
No problem for braves, that's secondary. Supporting chrome and chromium would be huge already.

Still, same problem with your new PR, I get an invalid padding byte error.
